include_defs('//solenv/maven/VERSION')
include_defs('//solenv/maven/package.defs')

URL = 'https://ossrh-staging-api.central.sonatype.com/content/repositories/snapshots' \
    if FREEDOMOFFICE_VERSION.endswith('-SNAPSHOT') else \
        'https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2'

maven_package(
  repository = 'ossrh-staging-api',
  url = URL,
  version = FREEDOMOFFICE_VERSION,
  jar = {
    'juh': '//:juh',
    'jurt': '//:jurt',
    'officebean': '//:officebean',
    'ridl': '//:ridl',
    'unoil': '//:unoil',
    'unoloader': '//:unoloader',
    'freedomoffice': '//:freedomoffice',
  },
  src = {
    'juh': '//javaunohelper:juh-src',
    'jurt': '//jurt:jurt-src',
    'officebean': '//bean:officebean-src',
    'ridl': '//ridljar:ridl-src',
    'unoil': '//unoil:unoil-src',
    'unoloader': '//ridljar/source/unoloader:unoloader-src',
    'freedomoffice': '//ridljar:freedomoffice-src',
  },
  doc = {
    'juh': '//javaunohelper:juh-javadoc',
    'jurt': '//jurt:jurt-javadoc',
    'officebean': '//bean:officebean-javadoc',
    'ridl': '//ridljar:ridl-javadoc',
    'unoil': '//unoil:unoil-javadoc',
    'unoloader': '//ridljar/source/unoloader:unoloader-javadoc',
    'freedomoffice': '//ridljar:freedomoffice-javadoc',
  },
)

python_binary(
  name = 'mvn',
  main = 'mvn.py',
)
