
java_sources(
  name = 'unoloader-src',
  srcs = glob(['com/**']),
  root = '.',
  visibility = ['PUBLIC'],
)

java_doc(
  name = 'unoloader-javadoc',
  title = 'FreedomOffice Uno loader',
  pkgs = [
    'com.sun.star.lib.unoloader',
  ],
  paths = ['.'],
  srcs = glob(['com/**']),
  deps = [
    '//:ridl',
  ],
  visibility = ['PUBLIC'],
)
